<?php
/**
 * @author Daniel Martinez <dani.dmd86@gmail.com>
 *
 * @package Dmd
 * @version 1
 */
$categoryId = $this->getCategoryId();
$products   = $this->getProducts($categoryId);
?>
<div class="cheapest-products">
    <h1><?php echo sprintf(__('Top %d cheapest products for %s'), $this->getNumberOfProductsToDisplay(), $this->getCategoryName($categoryId)); ?></h1>
    <?php if( $products->getSize() > 0 ) : ?>
        <ul>
            <?php foreach( $products as $product) : ?>
                <li><a href="<?php echo $product->getProductUrl(); ?>" target="_blank" title="<?php echo $product->getName(); ?>"><?php echo $product->getName(); ?></a></li>
            <?php endforeach; ?>
        </ul>
    <?php else: ?>
        <span><?php echo __('There are no products available.'); ?></span>
    <?php endif; ?>
</div>